const KEYBOARD = [
  [
    {
      id: '',
      base: '`',
      shift: '~',
      layoutBase: 'ё',
      layoutShift: 'Ё',
    },
    {
      id: '',
      base: '1',
      shift: '!',
      layoutBase: '1',
      layoutShift: '!',
    },
    {
      id: '',
      base: '2',
      shift: '@',
      layoutBase: '2',
      layoutShift: '"',
    },
    {
      id: '',
      base: '3',
      shift: '#',
      layoutBase: '3',
      layoutShift: '№',
    },
    {
      id: '',
      base: '4',
      shift: '$',
      layoutBase: '4',
      layoutShift: ';',
    },
    {
      id: '',
      base: '5',
      shift: '%',
      layoutBase: '5',
      layoutShift: '%',
    },
    {
      id: '',
      base: '6',
      shift: '^',
      layoutBase: '6',
      layoutShift: ':',
    },
    {
      id: '',
      base: '7',
      shift: '&',
      layoutBase: '7',
      layoutShift: '?',
    },
    {
      id: '',
      base: '8',
      shift: '*',
      layoutBase: '8',
      layoutShift: '*',
    },
    {
      id: '',
      base: '9',
      shift: '(',
      layoutBase: '9',
      layoutShift: '(',
    },
    {
      id: '',
      base: '-',
      shift: '_',
      layoutBase: '-',
      layoutShift: '_',
    },
    {
      id: '',
      base: '=',
      shift: '+',
      layoutBase: '=',
      layoutShift: '+',
    },
    {
      id: '',
      base: 'Backspace',
      shift: 'Backspace',
      layoutBase: 'Backspace',
      layoutShift: 'Backspace',
    },
  ],
  [
    {
      id: '',
      base: 'Tab',
      shift: 'Tab',
      layoutBase: 'Tab',
      layoutShift: 'Tab',
    },
    {
      id: '',
      base: 'q',
      shift: 'Q',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'w',
      shift: 'W',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'e',
      shift: 'E',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'r',
      shift: 'R',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 't',
      shift: 'T',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'y',
      shift: 'Y',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'u',
      shift: 'U',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'i',
      shift: 'I',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'o',
      shift: 'O',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'p',
      shift: 'P',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: '[',
      shift: '{',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: ']',
      shift: '}',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: '\\',
      shift: '|',
      layoutBase: '',
      layoutShift: '',
    },
  ],
  [
    {
      id: '',
      base: 'CapsLock',
      shift: 'CapsLock',
      layoutBase: 'CapsLock',
      layoutShift: 'CapsLock',
    },
    {
      id: '',
      base: 'a',
      shift: 'A',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 's',
      shift: 'S',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'd',
      shift: 'D',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'f',
      shift: 'F',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'g',
      shift: 'G',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'h',
      shift: 'H',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'j',
      shift: 'J',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'k',
      shift: 'K',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'l',
      shift: 'L',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: ';',
      shift: ':',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: '\'',
      shift: '"',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'Enter',
      shift: 'Enter',
      layoutBase: 'Enter',
      layoutShift: 'Enter',
    },
  ],
  [
    {
      id: '',
      base: 'Shift',
      shift: 'Shift',
      layoutBase: 'Shift',
      layoutShift: 'Shift',
    },
    {
      id: '',
      base: 'z',
      shift: 'Z',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'x',
      shift: 'X',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'c',
      shift: 'C',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'v',
      shift: 'V',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'b',
      shift: 'B',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'n',
      shift: 'N',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'm',
      shift: 'M',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: ',',
      shift: '<',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: '.',
      shift: '>',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: '/',
      shift: '?',
      layoutBase: '',
      layoutShift: '',
    },
    {
      id: '',
      base: 'ArrowUp',
      shift: 'ArrowUp',
      layoutBase: 'ArrowUp',
      layoutShift: 'ArrowUp',
    },
    {
      id: '',
      base: 'Shift',
      shift: 'Shift',
      layoutBase: 'Shift',
      layoutShift: 'Shift',
    },
  ],
  [
    {
      id: '',
      base: 'Ctrl',
      shift: 'Ctrl',
      layoutBase: 'Ctrl',
      layoutShift: 'Ctrl',
    },
    {
      id: '',
      base: 'Meta',
      shift: 'Meta',
      layoutBase: 'Meta',
      layoutShift: 'Meta',
    },
    {
      id: '',
      base: 'Alt',
      shift: 'Alt',
      layoutBase: 'Alt',
      layoutShift: 'Alt',
    },
    {
      id: '',
      base: ' ',
      shift: ' ',
      layoutBase: ' ',
      layoutShift: ' ',
    },
    {
      id: '',
      base: 'Alt',
      shift: 'Alt',
      layoutBase: 'Alt',
      layoutShift: 'Alt',
    },
    {
      id: '',
      base: 'Ctrl',
      shift: 'Ctrl',
      layoutBase: 'Ctrl',
      layoutShift: 'Ctrl',
    },
    {
      id: '',
      base: 'ArrowLeft',
      shift: 'ArrowLeft',
      layoutBase: 'ArrowLeft',
      layoutShift: 'ArrowLeft',
    },
    {
      id: '',
      base: 'ArrowDown',
      shift: 'ArrowDown',
      layoutBase: 'ArrowDown',
      layoutShift: 'ArrowDown',
    },
    {
      id: '',
      base: 'ArrowRight',
      shift: 'ArrowRight',
      layoutBase: 'ArrowRight',
      layoutShift: 'ArrowRight',
    },
  ],
];

export default KEYBOARD;
