const KEYBOARD = [
  [
    {
      id: 'Backquote',
      base: '`',
      shift: '~',
      layoutBase: 'ё',
      layoutShift: 'Ё',
    },
    {
      id: 'Digit1',
      base: '1',
      shift: '!',
      layoutBase: '1',
      layoutShift: '!',
    },
    {
      id: 'Digit2',
      base: '2',
      shift: '@',
      layoutBase: '2',
      layoutShift: '"',
    },
    {
      id: 'Digit3',
      base: '3',
      shift: '#',
      layoutBase: '3',
      layoutShift: '№',
    },
    {
      id: 'Digit4',
      base: '4',
      shift: '$',
      layoutBase: '4',
      layoutShift: ';',
    },
    {
      id: 'Digit5',
      base: '5',
      shift: '%',
      layoutBase: '5',
      layoutShift: '%',
    },
    {
      id: 'Digit6',
      base: '6',
      shift: '^',
      layoutBase: '6',
      layoutShift: ':',
    },
    {
      id: 'Digit7',
      base: '7',
      shift: '&',
      layoutBase: '7',
      layoutShift: '?',
    },
    {
      id: 'Digit8',
      base: '8',
      shift: '*',
      layoutBase: '8',
      layoutShift: '*',
    },
    {
      id: 'Digit9',
      base: '9',
      shift: '(',
      layoutBase: '9',
      layoutShift: '(',
    },
    {
      id: 'Digit0',
      base: '-',
      shift: '_',
      layoutBase: '-',
      layoutShift: '_',
    },
    {
      id: 'Equal',
      base: '=',
      shift: '+',
      layoutBase: '=',
      layoutShift: '+',
    },
    {
      id: 'Backspace',
      base: 'Backspace',
      shift: 'Backspace',
      layoutBase: 'Backspace',
      layoutShift: 'Backspace',
      extraClasses: [
        'key--control',
        'key--grow',
      ],
    },
  ],
  [
    {
      id: 'Tab',
      base: 'Tab',
      shift: 'Tab',
      layoutBase: 'Tab',
      layoutShift: 'Tab',
      extraClasses: [
        'key--control',
        'key--grow',
      ],
    },
    {
      id: 'KeyQ',
      base: 'q',
      shift: 'Q',
      layoutBase: 'й',
      layoutShift: 'Й',
    },
    {
      id: 'KeyW',
      base: 'w',
      shift: 'W',
      layoutBase: 'ц',
      layoutShift: 'Ц',
    },
    {
      id: 'KeyE',
      base: 'e',
      shift: 'E',
      layoutBase: 'у',
      layoutShift: 'У',
    },
    {
      id: 'KeyR',
      base: 'r',
      shift: 'R',
      layoutBase: 'к',
      layoutShift: 'К',
    },
    {
      id: 'KeyT',
      base: 't',
      shift: 'T',
      layoutBase: 'е',
      layoutShift: 'Е',
    },
    {
      id: 'KeyY',
      base: 'y',
      shift: 'Y',
      layoutBase: 'н',
      layoutShift: 'Н',
    },
    {
      id: 'KeyU',
      base: 'u',
      shift: 'U',
      layoutBase: 'г',
      layoutShift: 'Г',
    },
    {
      id: 'KeyI',
      base: 'i',
      shift: 'I',
      layoutBase: 'ш',
      layoutShift: 'Ш',
    },
    {
      id: 'KeyO',
      base: 'o',
      shift: 'O',
      layoutBase: 'щ',
      layoutShift: 'Щ',
    },
    {
      id: 'KeyP',
      base: 'p',
      shift: 'P',
      layoutBase: 'з',
      layoutShift: 'З',
    },
    {
      id: 'BracketLeft',
      base: '[',
      shift: '{',
      layoutBase: 'х',
      layoutShift: 'Х',
    },
    {
      id: 'BracketRight',
      base: ']',
      shift: '}',
      layoutBase: 'ъ',
      layoutShift: 'Ъ',
    },
    {
      id: 'Backslash',
      base: '\\',
      shift: '|',
      layoutBase: '\\',
      layoutShift: '/',
    },
    {
      id: 'Delete',
      base: 'Del',
      shift: 'Del',
      layoutBase: 'Del',
      layoutShift: 'Del',
      extraClasses: [
        'key--control',
        'key--grow',
      ],
    },
  ],
  [
    {
      id: 'CapsLock',
      base: 'CapsLock',
      shift: 'CapsLock',
      layoutBase: 'CapsLock',
      layoutShift: 'CapsLock',
      extraClasses: [
        'key--control',
        'key--grow',
      ],
    },
    {
      id: 'KeyA',
      base: 'a',
      shift: 'A',
      layoutBase: 'ф',
      layoutShift: 'Ф',
    },
    {
      id: 'KeyS',
      base: 's',
      shift: 'S',
      layoutBase: 'ы',
      layoutShift: 'Ы',
    },
    {
      id: 'KeyD',
      base: 'd',
      shift: 'D',
      layoutBase: 'в',
      layoutShift: 'В',
    },
    {
      id: 'KeyF',
      base: 'f',
      shift: 'F',
      layoutBase: 'а',
      layoutShift: 'А',
    },
    {
      id: 'KeyG',
      base: 'g',
      shift: 'G',
      layoutBase: 'п',
      layoutShift: 'П',
    },
    {
      id: 'KeyH',
      base: 'h',
      shift: 'H',
      layoutBase: 'р',
      layoutShift: 'Р',
    },
    {
      id: 'KeyJ',
      base: 'j',
      shift: 'J',
      layoutBase: 'о',
      layoutShift: 'О',
    },
    {
      id: 'KeyK',
      base: 'k',
      shift: 'K',
      layoutBase: 'л',
      layoutShift: 'Л',
    },
    {
      id: 'KeyL',
      base: 'l',
      shift: 'L',
      layoutBase: 'д',
      layoutShift: 'Д',
    },
    {
      id: 'Semicolon',
      base: ';',
      shift: ':',
      layoutBase: 'ж',
      layoutShift: 'Ж',
    },
    {
      id: 'Quote',
      base: '\'',
      shift: '"',
      layoutBase: 'э',
      layoutShift: 'Э',
    },
    {
      id: 'Enter',
      base: 'Enter',
      shift: 'Enter',
      layoutBase: 'Enter',
      layoutShift: 'Enter',
      extraClasses: [
        'key--control',
        'key--grow',
      ],
    },
  ],
  [
    {
      id: 'ShiftLeft',
      base: 'Shift',
      shift: 'Shift',
      layoutBase: 'Shift',
      layoutShift: 'Shift',
      extraClasses: [
        'key--control',
        'key--grow',
      ],
    },
    {
      id: 'KeyZ',
      base: 'z',
      shift: 'Z',
      layoutBase: 'я',
      layoutShift: 'Я',
    },
    {
      id: 'KeyX',
      base: 'x',
      shift: 'X',
      layoutBase: 'ч',
      layoutShift: 'Ч',
    },
    {
      id: 'KeyC',
      base: 'c',
      shift: 'C',
      layoutBase: 'с',
      layoutShift: 'С',
    },
    {
      id: 'KeyV',
      base: 'v',
      shift: 'V',
      layoutBase: 'м',
      layoutShift: 'М',
    },
    {
      id: 'KeyB',
      base: 'b',
      shift: 'B',
      layoutBase: 'и',
      layoutShift: 'И',
    },
    {
      id: 'KeyN',
      base: 'n',
      shift: 'N',
      layoutBase: 'т',
      layoutShift: 'Т',
    },
    {
      id: 'KeyM',
      base: 'm',
      shift: 'M',
      layoutBase: 'ь',
      layoutShift: 'Ь',
    },
    {
      id: 'Comma',
      base: ',',
      shift: '<',
      layoutBase: 'б',
      layoutShift: 'Б',
    },
    {
      id: 'Period',
      base: '.',
      shift: '>',
      layoutBase: 'ю',
      layoutShift: 'Ю',
    },
    {
      id: 'Slash',
      base: '/',
      shift: '?',
      layoutBase: '.',
      layoutShift: ',',
    },
    {
      id: 'ArrowUp',
      base: '↑',
      shift: '↑',
      layoutBase: '↑',
      layoutShift: '↑',
    },
    {
      id: 'ShiftRight',
      base: 'Shift',
      shift: 'Shift',
      layoutBase: 'Shift',
      layoutShift: 'Shift',
      extraClasses: [
        'key--control',
        'key--grow',
      ],
    },
  ],
  [
    {
      id: 'ControlLeft',
      base: 'Ctrl',
      shift: 'Ctrl',
      layoutBase: 'Ctrl',
      layoutShift: 'Ctrl',
      extraClasses: [
        'key--control',
      ],
    },
    {
      id: 'Meta',
      base: 'Meta',
      shift: 'Meta',
      layoutBase: 'Meta',
      layoutShift: 'Meta',
      extraClasses: [
        'key--control',
      ],
    },
    {
      id: 'AltLeft',
      base: 'Alt',
      shift: 'Alt',
      layoutBase: 'Alt',
      layoutShift: 'Alt',
      extraClasses: [
        'key--control',
      ],
    },
    {
      id: 'Space',
      base: ' ',
      shift: ' ',
      layoutBase: ' ',
      layoutShift: ' ',
      extraClasses: [
        'key--space',
      ],
    },
    {
      id: 'AltRight',
      base: 'Alt',
      shift: 'Alt',
      layoutBase: 'Alt',
      layoutShift: 'Alt',
      extraClasses: [
        'key--control',
      ],
    },
    {
      id: 'ArrowLeft',
      base: '←',
      shift: '←',
      layoutBase: '←',
      layoutShift: '←',
    },
    {
      id: 'ArrowDown',
      base: '↓',
      shift: '↓',
      layoutBase: '↓',
      layoutShift: '↓',
    },
    {
      id: 'ArrowRight',
      base: '→',
      shift: '→',
      layoutBase: '→',
      layoutShift: '→',
    },
    {
      id: 'ControlRight',
      base: 'Ctrl',
      shift: 'Ctrl',
      layoutBase: 'Ctrl',
      layoutShift: 'Ctrl',
      extraClasses: [
        'key--control',
      ],
    },
  ],
];

export default KEYBOARD;
